apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wsi-cluster
  region: ap-northeast-2
  version: "1.27"
  tags:
    karpenter.sh/discovery: wsi-cluster

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - cloudformation
    - logs

vpc:
  subnets:
    private:
      private-a:
          id: subnet-0220c3b755e1d7e9d
      private-b:
          id: subnet-0a09c54e4ed3af1c3
      private-c:
          id: subnet-04467be241636c414

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: allow-sa
      namespace: wsi
    roleName: allow-app-role
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AdministratorAccess

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

managedNodeGroups:
  - name: wsi-ng
    instanceName: wsi-node
    instanceType: c5.large
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    subnets:
      - private-a
      - private-b
      - private-c
    iam:
      withAddonPolicies:
        albIngress: true
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        awsLoadBalancerController: true
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly