apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /allowlist
        pathType: Prefix
        backend:
          service:
            name: allowlist
            port:
              number: 8080
      - path: /event
        pathType: Prefix
        backend:
          service:
            name: event
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 8080