apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  namespace: wsi
spec:
  selector:
    matchLabels:
      type: event
  replicas: 2
  template:
    metadata:
      labels:
        type: event
    spec:
      containers:
      - name: event-ctn
        image: 635867519280.dkr.ecr.ap-northeast-2.amazonaws.com/wsi-ecr:event
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"