apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
  namespace: wsi
spec:
  selector:
    matchLabels:
      type: event
  replicas: 2
  template:
    metadata:
      labels:
        type: event
    spec:
      containers:
      - name: event-ctn
        image: 
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m