apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wsi
  name: admin-rbac
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: wsi
  name: admin-rolebinding
subjects:
- kind: ServiceAccount
  name: admin-sa
  namespace: wsi
roleRef:
  kind: Role
  name: admin-rbac
  apiGroup: rbac.authorization.k8s.io