apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: wsi
spec:
  selector:
    matchLabels:
      type: user
  replicas: 2
  template:
    metadata:
      labels:
        type: user
    spec:
      containers:
      - name: user-ctn
        image: 635867519280.dkr.ecr.ap-northeast-2.amazonaws.com/wsi-ecr:user
        imagePullPolicy: Always
        env:
          - name: DB_WRITE_HOST
            value: wsi-db.cluster-c44tvborxnu4.ap-northeast-2.rds.amazonaws.com
          - name: DB_READ_HOST
            value: wsi-db.cluster-ro-c44tvborxnu4.ap-northeast-2.rds.amazonaws.com
          - name: DB_NAME
            value: dev
          - name: DB_USER
            value: skills
          - name: DB_PASSWORD
            value: Skills2024**
          - name: DB_PORT
            value: '5432'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"