apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: wsi
spec:
  selector:
    matchLabels:
      type: user
  replicas: 2
  template:
    metadata:
      labels:
        type: user
    spec:
      containers:
      - name: user-ctn
        image: 
        env:
          - name: DB_WRITE_HOST
            value: 
          - name: DB_READ_HOST
            value: 
          - name: DB_NAME
            value: skills
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-secret
                key: password 
          - name: DB_PORT
            value: '5432'
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m