apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wsi-cluster
  region: ap-northeast-2
  version: "1.27"
  tags:
    karpenter.sh/discovery: wsi-cluster

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-06f5a3e98089666eb
      ap-northeast-2b:
        id: subnet-0a8a822fd66e4c88b
      ap-northeast-2c:
        id: subnet-07dc08b6ea0a1d2d3

privateCluster:
  enabled: true
  additionalEndpointServices:
    - "autoscaling"
    - "cloudformation"
    - "logs"

iam:
  withOIDC: true

karpenter:
  version: '0.30.0'
  createServiceAccount: true

managedNodeGroups:
  - instanceType: t3.medium
    name: wsi-node-group
    instanceName: wsi-node
    desiredCapacity: 3
    minSize: 3
    maxSize: 16
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        awsLoadBalancerController: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]