apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wsi-cluster
  region: ap-northeast-2
  version: "1.27"
  tags:
    karpenter.sh/discovery: wsi-cluster

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - cloudformation
    - logs

vpc:
  subnets:
    private:
      ap-northeast-2a:
          id: 
      ap-northeast-2b:
          id: 
      ap-northeast-2c:
          id: 

iam:
  withOIDC: true

managedNodeGroups:
  - name: wsi-ng
    instanceName: wsi-node
    instanceType: c5.large
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    tags:
      karpenter.sh/discovery: wsi-cluster
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        awsLoadBalancerController: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]