apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wsi
  name: admin-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: wsi
  name: admin-role-binding
subjects:
- kind: User
  name: admin01
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io