apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wsi
  name: read-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: wsi
  name: read-role-binding
subjects:
- kind: User
  name: read01
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read
  apiGroup: rbac.authorization.k8s.io